// Mocks generated by Mockito 5.4.6 from annotations
// in dictionary_app/test/data/repositories/word_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:dictionary_app/core/services/connectivity_service.dart' as _i10;
import 'package:dictionary_app/core/utils/result.dart' as _i8;
import 'package:dictionary_app/data/local/daos/cached_api_dao.dart' as _i5;
import 'package:dictionary_app/data/local/daos/word_dao.dart' as _i2;
import 'package:dictionary_app/data/models/cached_api_model.dart' as _i6;
import 'package:dictionary_app/data/models/word_model.dart' as _i4;
import 'package:dictionary_app/data/remote/dictionary_api_service.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [WordDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockWordDao extends _i1.Mock implements _i2.WordDao {
  MockWordDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.WordModel?> getById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getById,
          [id],
        ),
        returnValue: _i3.Future<_i4.WordModel?>.value(),
      ) as _i3.Future<_i4.WordModel?>);

  @override
  _i3.Future<_i4.WordModel?> getByExactEnglish(String? english) =>
      (super.noSuchMethod(
        Invocation.method(
          #getByExactEnglish,
          [english],
        ),
        returnValue: _i3.Future<_i4.WordModel?>.value(),
      ) as _i3.Future<_i4.WordModel?>);

  @override
  _i3.Future<_i4.WordModel?> getByExactBangla(String? bangla) =>
      (super.noSuchMethod(
        Invocation.method(
          #getByExactBangla,
          [bangla],
        ),
        returnValue: _i3.Future<_i4.WordModel?>.value(),
      ) as _i3.Future<_i4.WordModel?>);

  @override
  _i3.Future<List<_i4.WordModel>> search({
    required String? query,
    int? limit = 30,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #search,
          [],
          {
            #query: query,
            #limit: limit,
          },
        ),
        returnValue: _i3.Future<List<_i4.WordModel>>.value(<_i4.WordModel>[]),
      ) as _i3.Future<List<_i4.WordModel>>);

  @override
  _i3.Future<List<_i4.WordModel>> getByCategory(
    int? categoryId, {
    int? limit = 200,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getByCategory,
          [categoryId],
          {
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue: _i3.Future<List<_i4.WordModel>>.value(<_i4.WordModel>[]),
      ) as _i3.Future<List<_i4.WordModel>>);

  @override
  _i3.Future<List<_i4.WordModel>> getMostSearched({int? limit = 10}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMostSearched,
          [],
          {#limit: limit},
        ),
        returnValue: _i3.Future<List<_i4.WordModel>>.value(<_i4.WordModel>[]),
      ) as _i3.Future<List<_i4.WordModel>>);

  @override
  _i3.Future<_i4.WordModel?> getRandomWord({required int? seed}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRandomWord,
          [],
          {#seed: seed},
        ),
        returnValue: _i3.Future<_i4.WordModel?>.value(),
      ) as _i3.Future<_i4.WordModel?>);

  @override
  _i3.Future<int> insert(_i4.WordModel? word) => (super.noSuchMethod(
        Invocation.method(
          #insert,
          [word],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> update(_i4.WordModel? word) => (super.noSuchMethod(
        Invocation.method(
          #update,
          [word],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> updateEnrichment(_i4.WordModel? word) => (super.noSuchMethod(
        Invocation.method(
          #updateEnrichment,
          [word],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<void> incrementSearchCount(int? wordId) => (super.noSuchMethod(
        Invocation.method(
          #incrementSearchCount,
          [wordId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<int> getTotalWordCount() => (super.noSuchMethod(
        Invocation.method(
          #getTotalWordCount,
          [],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> getSyncedWordCount() => (super.noSuchMethod(
        Invocation.method(
          #getSyncedWordCount,
          [],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);
}

/// A class which mocks [CachedApiDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockCachedApiDao extends _i1.Mock implements _i5.CachedApiDao {
  MockCachedApiDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> hasCachedResponse(int? wordId) => (super.noSuchMethod(
        Invocation.method(
          #hasCachedResponse,
          [wordId],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<void> save(_i6.CachedApiModel? cached) => (super.noSuchMethod(
        Invocation.method(
          #save,
          [cached],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [DictionaryApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDictionaryApiService extends _i1.Mock
    implements _i7.DictionaryApiService {
  MockDictionaryApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i8.Result<Map<String, dynamic>>> fetchWordData(String? english) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchWordData,
          [english],
        ),
        returnValue: _i3.Future<_i8.Result<Map<String, dynamic>>>.value(
            _i9.dummyValue<_i8.Result<Map<String, dynamic>>>(
          this,
          Invocation.method(
            #fetchWordData,
            [english],
          ),
        )),
      ) as _i3.Future<_i8.Result<Map<String, dynamic>>>);
}

/// A class which mocks [ConnectivityService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivityService extends _i1.Mock
    implements _i10.ConnectivityService {
  MockConnectivityService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<bool> get onStatusChange => (super.noSuchMethod(
        Invocation.getter(#onStatusChange),
        returnValue: _i3.Stream<bool>.empty(),
      ) as _i3.Stream<bool>);

  @override
  _i3.Future<bool> isOnline() => (super.noSuchMethod(
        Invocation.method(
          #isOnline,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
